apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: '1.14.x'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  values:
    provider: aws
    aws:
      region: us-east-1
      zoneType: public
    serviceAccount:
      create: true
      name: external-dns
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::586794457112:role/sre-capstone-dev-cluster-external-dns"  # Update from terraform output
    policy: sync
    sources:
      - service
      - ingress
    domainFilters:
      - yourdomain.com  # Update with your domain
    txtOwnerId: sre-capstone-dev
    logLevel: info
    interval: 1m