apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-load-balancer-controller-simple.yaml
  - external-secrets.yaml
  - prometheus-stack-simple.yaml
  - loki.yaml
  - opentelemetry-tempo.yaml
  - prometheus-rules-slo.yaml
  - prometheus-alerts.yaml