apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service-loadbalancer.yaml
  - hpa-pdb.yaml
  - external-secret.yaml
  - network-policy.yaml
  - servicemonitor.yaml